### ISSUE TITLE
Bug in padding of replaceVariables

### ISSUE THREAD

**Issue by Bouloulou1138** [mdibaiee/mathexpr#3]
Hello @mdibaiee ,

There is a bug in replaceVariables, it does not add padding in otherwise clause, which causes issues in parsing in the later functions.
I want to open a pull request to fix the issue, but I do not think I have the necessary permissions.

Could you grant me permission to open the pull request?
Or you can fix the issue yourself, no problem by me.

**Comment by mdibaiee** [comment]
Hello @Bouloulou1138 , I believe you can fork the repository, make your changes and create a pull-request from your fork into this repository. I will be happy to review 👍🏽

**Comment by Bouloulou1138** [comment]
Thanks, I just created one:
https://github.com/mdibaiee/mathexpr/pull/4
